---
title: "Weather Anomalies Study"
author: "Alessandro Angeletti"
date: "2020-09-18"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: hide
categories:
- Weather Analysis
draft: false
image: images/portfolio/climate.jpg
---



<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<blockquote>
<p>To study climate change, we found data on the Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies in the Northern Hemisphere at NASA’s Goddard Institute for Space Studies.</p>
</blockquote>
<p>The first step was to import the messy <strong>data</strong> which can be seen below</p>
<pre><code>## # A tibble: 140 x 19
##     Year   Jan    Feb    Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov
##    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  1880 -0.54 -0.38  -0.26  -0.37 -0.11 -0.22 -0.23 -0.24 -0.26 -0.32 -0.37
##  2  1881 -0.19 -0.25   0.02  -0.02 -0.06 -0.36 -0.06 -0.03 -0.23 -0.4  -0.42
##  3  1882  0.22  0.22   0     -0.36 -0.32 -0.38 -0.37 -0.14 -0.17 -0.53 -0.32
##  4  1883 -0.59 -0.67  -0.16  -0.27 -0.32 -0.26 -0.09 -0.26 -0.33 -0.21 -0.4 
##  5  1884 -0.23 -0.11  -0.65  -0.62 -0.42 -0.52 -0.48 -0.5  -0.45 -0.41 -0.48
##  6  1885 -1    -0.37  -0.21  -0.53 -0.55 -0.47 -0.39 -0.44 -0.32 -0.3  -0.28
##  7  1886 -0.68 -0.68  -0.570 -0.34 -0.34 -0.43 -0.2  -0.47 -0.34 -0.31 -0.45
##  8  1887 -1.07 -0.580 -0.36  -0.42 -0.27 -0.2  -0.23 -0.52 -0.17 -0.4  -0.19
##  9  1888 -0.53 -0.59  -0.580 -0.24 -0.16 -0.04  0.04 -0.19 -0.12  0.04 -0.03
## 10  1889 -0.31  0.35   0.07   0.15 -0.05 -0.12 -0.1  -0.16 -0.26 -0.34 -0.61
## # ... with 130 more rows, and 7 more variables: Dec &lt;dbl&gt;, `J-D` &lt;dbl&gt;,
## #   `D-N` &lt;dbl&gt;, DJF &lt;dbl&gt;, MAM &lt;dbl&gt;, JJA &lt;dbl&gt;, SON &lt;dbl&gt;</code></pre>
<p>Next, we <strong>cleaned</strong> the dataset - discarded unwanted columns and converted the wide format to a long format.</p>
<pre><code>## # A tibble: 140 x 13
##     Year   Jan    Feb    Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov
##    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  1880 -0.54 -0.38  -0.26  -0.37 -0.11 -0.22 -0.23 -0.24 -0.26 -0.32 -0.37
##  2  1881 -0.19 -0.25   0.02  -0.02 -0.06 -0.36 -0.06 -0.03 -0.23 -0.4  -0.42
##  3  1882  0.22  0.22   0     -0.36 -0.32 -0.38 -0.37 -0.14 -0.17 -0.53 -0.32
##  4  1883 -0.59 -0.67  -0.16  -0.27 -0.32 -0.26 -0.09 -0.26 -0.33 -0.21 -0.4 
##  5  1884 -0.23 -0.11  -0.65  -0.62 -0.42 -0.52 -0.48 -0.5  -0.45 -0.41 -0.48
##  6  1885 -1    -0.37  -0.21  -0.53 -0.55 -0.47 -0.39 -0.44 -0.32 -0.3  -0.28
##  7  1886 -0.68 -0.68  -0.570 -0.34 -0.34 -0.43 -0.2  -0.47 -0.34 -0.31 -0.45
##  8  1887 -1.07 -0.580 -0.36  -0.42 -0.27 -0.2  -0.23 -0.52 -0.17 -0.4  -0.19
##  9  1888 -0.53 -0.59  -0.580 -0.24 -0.16 -0.04  0.04 -0.19 -0.12  0.04 -0.03
## 10  1889 -0.31  0.35   0.07   0.15 -0.05 -0.12 -0.1  -0.16 -0.26 -0.34 -0.61
## # ... with 130 more rows, and 1 more variable: Dec &lt;dbl&gt;</code></pre>
<pre><code>## # A tibble: 1,680 x 3
##     Year month delta
##    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1  1880 Jan   -0.54
##  2  1880 Feb   -0.38
##  3  1880 Mar   -0.26
##  4  1880 Apr   -0.37
##  5  1880 May   -0.11
##  6  1880 Jun   -0.22
##  7  1880 Jul   -0.23
##  8  1880 Aug   -0.24
##  9  1880 Sep   -0.26
## 10  1880 Oct   -0.32
## # ... with 1,670 more rows</code></pre>
<p>On further inspection, our dataframe has three variables now - one each for year, month and delta (temperature deviation).</p>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<blockquote>
<p>We plotted the data using a time-series scatter plot, and added a trendline. We used ‘lubridate’ for dates to ensure that delta plots chronologically.</p>
</blockquote>
<p><img src="/portfolio/Weather_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Next, we studied the effect of increasing temperature by month.</p>
</blockquote>
<p><img src="/portfolio/Weather_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Overall, we see a gradual rise in the average temperature across all twelve months from 1880 to 2019 owing to Global Warming. This rise has been greater for winter months such as January, February, November and December, compared to summer months such as May, June, July and August.</p>
</blockquote>
<blockquote>
<p>Another point worth mentioning is that the winter months depict greater deviation (the points are more scattered around the trendline) compared to summer months which have relatively lower deviation (the points are closer to the trendline)</p>
</blockquote>
<p>Since it is sometimes useful to group data into different time periods to study historical data, we created a new data frame called <code>comparison</code> that groups data into five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<pre><code>## # A tibble: 1,668 x 5
##     Year month delta date       interval 
##    &lt;dbl&gt; &lt;ord&gt; &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt;    
##  1  1881 Jan   -0.19 1881-01-01 1881-1920
##  2  1881 Feb   -0.25 1881-02-01 1881-1920
##  3  1881 Mar    0.02 1881-03-01 1881-1920
##  4  1881 Apr   -0.02 1881-04-01 1881-1920
##  5  1881 May   -0.06 1881-05-01 1881-1920
##  6  1881 Jun   -0.36 1881-06-01 1881-1920
##  7  1881 Jul   -0.06 1881-07-01 1881-1920
##  8  1881 Aug   -0.03 1881-08-01 1881-1920
##  9  1881 Sep   -0.23 1881-09-01 1881-1920
## 10  1881 Oct   -0.4  1881-10-01 1881-1920
## # ... with 1,658 more rows</code></pre>
<blockquote>
<p>Once we had intervals, we studied the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we were interested in.</p>
</blockquote>
<p><img src="/portfolio/Weather_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Later, we studied average annual anomalies as well.</p>
</blockquote>
<p><img src="/portfolio/Weather_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>We constructed a confidence interval for the average annual ‘delta’ since 2011, using two different methods</p>
<p><em>(1) a formula</em></p>
<pre class="r"><code>formula_CI &lt;- comparison %&gt;% 
                filter(interval==&quot;2011-present&quot;) %&gt;% # filter for time period we&#39;re interested in
                summarise(mean=mean(delta, na.rm=TRUE), # calculate summary statistics for delta
                          SD=sd(delta, na.rm=TRUE), 
                          count=n(), 
                          SE=SD/sqrt(count),
                          lower_CI = mean - 1.96*SE,
                          upper_CI = mean + 1.96*SE
                          ) %&gt;% 
  skim()

formula_CI</code></pre>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
(#tab:calculate_CI_using_formula)Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:right;">
0.97
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
SD
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
count
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
108.00
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
108.00
</td>
<td style="text-align:right;">
108.00
</td>
<td style="text-align:right;">
108.00
</td>
<td style="text-align:right;">
108.00
</td>
<td style="text-align:right;">
108.00
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
SE
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:right;">
0.03
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
lower_CI
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
upper_CI
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
</tbody>
</table>
<p><em>(2) bootstrap simulation with the <code>infer</code> package</em></p>
<pre class="r"><code># use the infer package to construct a 95% CI for delta
library(infer)

set.seed(1234)
whatever_id_like &lt;- comparison %&gt;% 
  filter(interval==&quot;2011-present&quot;) %&gt;%      # filtering for time period we&#39;re interested in
  specify(response=delta) %&gt;%               # specifying what we&#39;re calculating CI for
  generate(reps=1000, type=&quot;bootstrap&quot;) %&gt;% # generate random samples or reps using bootstrap
  calculate(stat=&quot;mean&quot;)                    # calculate mean
  
percentile_CI &lt;- whatever_id_like %&gt;% 
                 get_confidence_interval(comparison$delta, level=0.95, type=&quot;percentile&quot;) %&gt;% 
  skim()

percentile_CI</code></pre>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
(#tab:calculate_CI_using_bootstrap)Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
lower_ci
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
upper_ci
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:right;">
1.02
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2581&gt;&lt;U+2587&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>The first method calculates summary statistics and confidence intervals (CI) using the whole data for temperature deviations (delta) from 2011 to present. On the other hand, the bootstrap method creates 1000 random samples (reps), and calculates their means on the basis of which we arrive at CIs.</p>
</blockquote>
<blockquote>
<p>The 95% lower CI and upper CI is 0.917 and 1.02 respectively, which means that out of every 1000 samples, we are confident that for 950 samples the range [0.917, 1.02] would correctly contain the true mean of the population.</p>
</blockquote>
</div>
</div>
